// ═══════════════════════════════════════════════════════════════════════════════
// WEDJAT v4 — ADDITIVE production Turso migration (§76: ADD, never DESTROY).
//
// Applies the v4 Intelligence-Fabric schema to the remote Turso database:
//   • CREATE TABLE IF NOT EXISTS for the 8 new v4 tables (+ indexes/uniques)
//   • ALTER TABLE … ADD COLUMN for the Platform registry columns (nullable)
//   • NEVER drops, truncates or rewrites any existing table/row (§5/§6/§75 —
//     production knowledge/history stays byte-identical)
//
// Idempotent: safe to re-run. DDL is extracted from the local SQLite (the
// authoritative schema generated by `prisma db push`).
//
// Usage:
//   bun scripts/migrate-v4-turso.ts          (reads .env.local WEDJAT_TURSO_*)
// ═══════════════════════════════════════════════════════════════════════════════

import { createClient } from '@libsql/client';
import { readFileSync } from 'node:fs';

const env = readFileSync('.env.local', 'utf8');
const envMap = new Map(
  env.split('\n')
    .filter((l) => l.includes('=') && !l.trim().startsWith('#'))
    .map((l) => {
      const i = l.indexOf('=');
      return [l.slice(0, i).trim(), l.slice(i + 1).trim()];
    })
);
const TURSO_URL = process.env.TURSO_DATABASE_URL ?? envMap.get('WEDJAT_TURSO_DATABASE_URL');
const TURSO_TOKEN = process.env.TURSO_AUTH_TOKEN ?? envMap.get('WEDJAT_TURSO_AUTH_TOKEN');
if (!TURSO_URL || !TURSO_TOKEN) {
  console.error('Need WEDJAT_TURSO_DATABASE_URL / WEDJAT_TURSO_AUTH_TOKEN (env or .env.local)');
  process.exit(1);
}

const local = createClient({ url: process.env.DATABASE_URL ?? 'file:db/custom.db' });
const remote = createClient({ url: TURSO_URL, authToken: TURSO_TOKEN });

const V4_TABLES = [
  'ServiceIdentity', 'EventRecord', 'DeadLetterEvent', 'Recommendation',
  'RecommendationOutcome', 'OrgPattern', 'KnowledgeGap', 'KnowledgeLineage',
];

const PLATFORM_COLUMNS: { column: string; ddl: string }[] = [
  { column: 'repositoryUrl', ddl: '"repositoryUrl" TEXT' },
  { column: 'deploymentUrl', ddl: '"deploymentUrl" TEXT' },
  { column: 'databaseUrl', ddl: '"databaseUrl" TEXT' },
  { column: 'connectionStatus', ddl: '"connectionStatus" TEXT' },
  { column: 'registryMetaJson', ddl: '"registryMetaJson" TEXT DEFAULT \'{}\'' },
];

async function main(): Promise<void> {
  await remote.execute('SELECT 1');
  console.log('✓ remote Turso reachable:', TURSO_URL);

  // Snapshot pre-migration state (evidence for the §125 audit).
  const before = await countAll(remote);
  console.log(`✓ pre-migration row counts: ${JSON.stringify(before)}`);

  // 1. Create v4 tables (idempotent).
  const localTables = await local.execute(
    "SELECT name, sql FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'"
  );
  const ddlByTable = new Map(localTables.rows.map((r) => [String(r.name), String(r.sql)]));
  const remoteTables = new Set(
    (await remote.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'")).rows.map((r) => String(r.name))
  );
  let created = 0;
  for (const t of V4_TABLES) {
    const ddl = ddlByTable.get(t);
    if (!ddl) throw new Error(`local schema missing v4 table ${t}`);
    if (remoteTables.has(t)) {
      console.log(`  · ${t} exists (skipped)`);
      continue;
    }
    await remote.execute(ddl);
    created += 1;
    console.log(`  + ${t} created`);
  }

  // 2. Additive Platform columns (ALTER TABLE ADD COLUMN — SQLite supports
  //    only single-column adds; skip existing columns).
  const platformCols = new Set(
    (await remote.execute('PRAGMA table_info(Platform)')).rows.map((r) => String(r.name))
  );
  for (const c of PLATFORM_COLUMNS) {
    if (platformCols.has(c.column)) {
      console.log(`  · Platform.${c.column} exists (skipped)`);
      continue;
    }
    await remote.execute(`ALTER TABLE Platform ADD COLUMN ${c.ddl}`);
    console.log(`  + Platform.${c.column} added`);
  }

  // 3. v4 indexes + unique constraints (from local sqlite_master).
  const localIdx = await local.execute(
    "SELECT name, sql FROM sqlite_master WHERE type='index' AND sql IS NOT NULL AND tbl_name IN ('ServiceIdentity','EventRecord','DeadLetterEvent','Recommendation','RecommendationOutcome','OrgPattern','KnowledgeGap','KnowledgeLineage')"
  );
  const remoteIdx = new Set(
    (await remote.execute("SELECT name FROM sqlite_master WHERE type='index'")).rows.map((r) => String(r.name))
  );
  let idxCreated = 0;
  for (const r of localIdx.rows) {
    const name = String(r.name);
    if (remoteIdx.has(name)) continue;
    await remote.execute(String(r.sql));
    idxCreated += 1;
  }
  console.log(`✓ indexes ensured: ${idxCreated} created`);

  // 4. Post-migration verification: NO existing rows changed.
  const after = await countAll(remote);
  const preExisting = Object.keys(after).filter((k) => !V4_TABLES.includes(k));
  let unchanged = true;
  for (const k of preExisting) {
    if ((after[k] ?? 0) !== (before[k] ?? 0)) {
      unchanged = false;
      console.error(`  ✗ ${k}: row count changed ${before[k]} → ${after[k]}`);
    }
  }
  console.log(unchanged
    ? `✓ §125 AUDIT: all pre-existing tables unchanged (${preExisting.length} tables verified)`
    : '✗ ROW COUNT REGRESSION DETECTED — inspect before proceeding');
  if (!unchanged) process.exit(1);

  console.log(`✓ v4 migration complete: ${created} new tables, ${idxCreated} indexes, 0 deletions, 0 overwrites.`);
  await local.close();
  await remote.close();
}

async function countAll(client: ReturnType<typeof createClient>): Promise<Record<string, number>> {
  const tables = (await client.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'")).rows.map((r) => String(r.name));
  const counts: Record<string, number> = {};
  for (const t of tables) {
    const n = await client.execute(`SELECT COUNT(*) AS n FROM "${t}"`).catch(() => null);
    if (n) counts[t] = Number(n.rows[0].n);
  }
  return counts;
}

main().catch((e) => {
  console.error('MIGRATION FAILED:', e instanceof Error ? e.message : e);
  process.exit(1);
});
